hw-5-mvc/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  resources :likes, only: [:create, :destroy]
  resources :tweets do
    resources :comments, only: [:create, :destroy]
    resource :like, only: [:create, :destroy]
    # resources :likes, only: [:create, :destroy], defaults: { likable: 'Tweet' }
  end
  # resources :comments do
  #   resources :likes, only: [:create, :destroy]
  # end

  resource  :user_profiles, only: %i[edit update]
  resources :tweets
  resources :comments, only: [:create, :destroy]

  root to: 'home#index'
end

hw-5-mvc/app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index
    @user_profile = current_user.user_profile
    @tweets       = Tweet.all.reverse
    @users        = User.all.except(current_user)
  end
end

hw-5-mvc/app/views/home/_profile_info.html.erb
<div class="card">
  <div class="card-body">
    <h3 class="card-title">
      <%= profile.username %>
    </h3>
    <h6 class="card-subtitle mb-2 text-muted">
      <%= profile.first_name %>
      <%= profile.last_name %>
    </h6>
    <hr>

    <p class="card-text">
          <span>
            <strong>Date of birth:</strong>
          </span>
      <span>
            <%= profile.birthday&.strftime('%D') %>
          </span>
    </p>
    <p class="card-text">
      <strong>Bio:</strong>
      <%= profile.bio %>
    </p>
    <hr>
    <p class="card-text my-tweets-section">
      <strong>
        <%= link_to 'My Tweets', tweets_path, class: 'card-link' %>:
      </strong>
      <%= profile.user.tweets.count %>
    </p>
    <hr>

    <%= link_to 'Edit', edit_user_profiles_path, class: 'card-link' %>
  </div>
</div>

hw-5-mvc/app/views/home/_profile_preview.html.erb
<h6>
  <strong>
    <%= user.user_profile.first_name %>
    <%= user.user_profile.last_name %>
  </strong>
  @<%= user.user_profile.username %>
</h6>
<hr>

hw-5-mvc/app/views/home/_users_list.html.erb
<h4>Who is here?</h4>
<hr>
<%= render partial: 'home/profile_preview', collection: users, as: :user %>

hw-5-mvc/app/views/home/index.html.erb
<div class="row">
  <div class="col-md-3">
    <%= render 'home/profile_info', profile: current_user.user_profile %>
  </div>

  <div class="col-md-6 mt-4">

    <hr>

    <%= render partial: 'tweets/tweet_preview', collection: @tweets, as: :tweet %>
  </div>

  <%= render 'tweets/form' %>

  <div class="col-md-3">
    <%= render 'home/users_list', users: @users %>
  </div>
</div>