hw-5-mvc/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  resources :likes, only: [:create, :destroy]
  resources :tweets do
    resources :comments, only: [:create, :destroy]
    resource :like, only: [:create, :destroy]
    # resources :likes, only: [:create, :destroy], defaults: { likable: 'Tweet' }
  end
  # resources :comments do
  #   resources :likes, only: [:create, :destroy]
  # end

  resource  :user_profiles, only: %i[edit update]
  resources :tweets
  resources :comments, only: [:create, :destroy]

  root to: 'home#index'
end

hw-5-mvc/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :tweet
  has_many :likes, as: :likable, dependent: :destroy
end

hw-5-mvc/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_tweet, only: [:edit, :update, :destroy]
  before_action :authorize_user, only: [:edit, :update, :destroy]
  before_action :set_comment, only: [:edit, :update, :destroy]

  def edit
    @comment = Comment.find(params[:id])
    @comments = @comment.tweet.comments.includes(:user).order(created_at: :desc)
  end

  def update
    if @comment.update(comment_params)
      flash[:notice] = "Comment updated successfully."
      redirect_to root_path
    else
      flash.now[:alert] = @comment.errors.full_messages.to_sentence
      render :edit
    end
  end

  def new
    @tweet = Tweet.find(params[:tweet_id])
    @comment = Comment.new
  end

  def destroy
    @comment = Comment.find(params[:id])

    if @comment.user == current_user
      @comment.destroy
      flash[:notice] = "Comment deleted successfully."
    else
      flash[:alert] = "You are not authorized to delete this comment."
    end

    redirect_to root_path
  end

  def create
    @tweet = Tweet.find(params[:tweet_id])
    @comment = @tweet.comments.new(comment_params.merge(user: current_user))

    if @comment.save
      flash.now[:notice] = "Comment added successfully."
    else
      flash.now[:alert] = @comment.errors.full_messages.to_sentence
    end

    @comments = @tweet.comments.includes(:user).order(created_at: :desc) # Оновлюємо список коментарів
    redirect_to root_path
  end

  private

  def set_tweet
    @tweet = Tweet.find(params[:tweet_id])
  end
  def set_comment
    @comment = Comment.find(params[:id])
  end
  def comment_params
    params.require(:comment).permit(:content)
  end
  def authorize_user
    @comment = Comment.find(params[:id])
    unless @comment.user == current_user
      redirect_to root_path, alert: "You are not authorized to perform this action."
    end
  end
end

hw-5-mvc/app/views/comments/_add.html.erb
<% if current_user %>
  <%= form_with model: [tweet, Comment.new], local: true do |f| %>
    <div class="form-group">
      <%= f.label :content, "Your Comment" %>
      <%= f.text_area :content, rows: 3, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.submit "comment", class: "btn btn-primary" %>
    </div>
  <% end %>
<% else %>
  <p>You need to <a href="/login">log in</a> to add a comment.</p>
<% end %>

hw-5-mvc/app/views/comments/_delete.html.erb
<!--<p>-->
  <%#= button_to "Delete", tweet_comment_path(tweet, comment), method: :delete, data: { confirm: "Are you sure you want to delete this comment?" }, class: "btn btn-danger btn-sm mt-2" %>
<!--</p>-->
<%= form_with(model: [tweet, comment], method: :delete, local: true) do %>
  <%= submit_tag "Delete", class: "btn btn-danger btn-sm" %>
<% end %>

hw-5-mvc/app/views/comments/_edit.html.erb
<p>
  <% if comment.user == current_user %>
    <strong>@<%= comment.user.user_profile.username %></strong>:
    <%= form_with(model: [tweet, comment], method: :patch, local: true, class: "comment-update-form") do |form| %>
      <%= form.text_area :content, value: comment.content, rows: 1, class: "form-control", id: "edit_comment_#{comment.id}" %>
      <div class="row">
        <%= form.submit "Update", class: "btn btn-primary btn-sm mt-2 h-100 m-2" %>
        <%= render partial: "comments/delete", locals: { tweet: tweet, comment: comment } %>
      </div>
    <% end %>
  <% else %>
    <p class="comment-content">
      <strong>@<%= comment.user.user_profile.username %></strong>: <%= comment.content %>
    </p>
  <% end %>
  </p>