hw-5-mvc/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  resources :likes, only: [:create, :destroy]
  resources :tweets do
    resources :comments, only: [:create, :destroy]
    resource :like, only: [:create, :destroy]
    # resources :likes, only: [:create, :destroy], defaults: { likable: 'Tweet' }
  end
  # resources :comments do
  #   resources :likes, only: [:create, :destroy]
  # end

  resource  :user_profiles, only: %i[edit update]
  resources :tweets
  resources :comments, only: [:create, :destroy]

  root to: 'home#index'
end

hw-5-mvc/app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :likable, polymorphic: true

  validates :user_id, uniqueness: { scope: [:likable_id, :likable_type], message: "You can like this only once." }
end

hw-5-mvc/app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_likable, only: :create

  def create
    @likable = params[:likable].safe_constantize.find(params[:likable_id])
    @like = @likable.likes.build(user: current_user)

    if @like.save
      flash[:notice] = "Liked successfully."
    else
      flash[:alert] = "Unable to like."
    end

    redirect_back(fallback_location: root_path)
  end


  def destroy
    @like = Like.find(params[:id])

    if @like.destroy
      flash[:notice] = "Disliked successfully."
    else
      flash[:alert] = "Unable to dislike."
    end

    redirect_back(fallback_location: root_path)
  end


  private

  def set_likable
    klass = params[:likable].safe_constantize
    raise ActionController::BadRequest, "Invalid likable type" unless klass

    @likable = klass.find(params[:likable_id])
  end
end

hw-5-mvc/app/helpers/likes_helper.rb
module LikesHelper
end

hw-5-mvc/app/views/likes/_like.html.erb
<!--<div class="tweet-actions">-->
<!--  <p>Likes: <%#= tweet.likes.count %></p>-->
  <%# if current_user.liked_tweets.exists?(id: tweet.id) %>
    <%#= button_to tweet_like_path(tweet), method: :delete, class: "btn bg-transparent mb-3 p-0" do %>
      <%#= image_tag "dislike.svg", alt: "Dislike", class: "dislike-icon" %>
    <%# end %>
  <%# else %>
    <%#= button_to tweet_like_path(tweet), method: :post, class: "btn bg-transparent mb-3 p-0" do %>
      <%#= image_tag "like.svg", alt: "Like", class: "like-icon" %>
    <%# end %>
  <%# end %>
<!--</div>-->

<% like = current_user.likes.find_by(likable: likable) %>

<% if like %>
  <%= form_with url: like_path(id: like.id), method: :delete do %>
    <%= submit_tag "Dislike", class: "btn btn-danger mt-3" %>
  <% end %>
<% else %>
  <%= form_with url: likes_path, method: :post do %>
    <%= hidden_field_tag :likable, likable.class.name %>
    <%= hidden_field_tag :likable_id, likable.id %>
    <%= submit_tag "Like", class: "btn btn-primary mb-3" %>
  <% end %>
<% end %>